before_install:
  - chmod +x build.sh
  
language: node_js
node_js:
  - "node"

script: ./build.sh

cache: npm

deploy:
  provider: npm
  email: "667@onezerohosting.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
